# Generated by Django 3.1 on 2020-08-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacias_turno_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmacia',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
    ]
